language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - export PIP_INDEX_URL=https://simple.crate.io/
install:
  - pip install https://github.com/django/django/zipball/stable/$DJANGO_VERSION.x --use-mirrors
  - pip install -e .
script:
  - make test
env:
  - DJANGO_VERSION=1.1
  - DJANGO_VERSION=1.2
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
branches:
  only:
    - master
matrix:
  exclude:
    - python: "2.5"
      env: DJANGO_VERSION=1.5
    - python: "2.5"
      env: DJANGO_VERSION=1.6
    - python: "3.2"
      env: DJANGO_VERSION=1.1
    - python: "3.2"
      env: DJANGO_VERSION=1.2
    - python: "3.2"
      env: DJANGO_VERSION=1.3
    - python: "3.2"
      env: DJANGO_VERSION=1.4
    - python: "3.3"
      env: DJANGO_VERSION=1.1
    - python: "3.3"
      env: DJANGO_VERSION=1.2
    - python: "3.3"
      env: DJANGO_VERSION=1.3
    - python: "3.3"
      env: DJANGO_VERSION=1.4