language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
before_install:
  - export PIP_INDEX_URL=https://simple.crate.io/
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e .
script:
  - make test
env:
  - DJANGO_VERSION=1.0.4
  - DJANGO_VERSION=1.1.4
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5
branches:
  only:
    - master
matrix:
  exclude:
    - python: "2.5"
      env: DJANGO_VERSION=1.5
