language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install:
  - pip install Django==$DJANGO
  - pip install -e .
script:
  - make test-django-$SETTINGS_VERSION
env:
  - DJANGO_VERSION=1.2.7 SETTINGS_VERSION=1-2
  - DJANGO_VERSION=1.3.1 SETTINGS_VERSION=1-3
  - DJANGO_VERSION=1.4   SETTINGS_VERSION=1-4
branches:
  only:
    - master